### ISSUE TITLE
Web version does not have login with Apple

### ISSUE THREAD

**Issue by rinchen** [Free-Republic-of-Verdis/verdis-communications#11]
I logged in with Apple on iOS but that option is not available in the web version, thus, I cannot login to the web.

**Comment by garv-shah** [comment]
so, you can login, you just have to reset ur password, since if you signed in with apple, you don't have a password
I can also reset ur password for you if you'd like
I *think* it's possible to add Sign In with Apple to the web, but I'm not too sure since the docs kinda suck, and I'm not sure how it'd work on non apple devices
I'll try it out and get back to you though

**Comment by garv-shah** [comment]
yeah, I don't think it's possible rn
well it probably is possible, just a lot more effort than it's worth, since [this package](https://pub.dev/packages/flutterfire_ui) doesn't support it (check out the [interactive example](https://flutterfire-ui.web.app/) to see what I'm talking about).
again, I'm happy to accept prs if you want to redesign the whole login screen, but I don't have the effort to do so, so I'll close this issue for now
