### ISSUE TITLE
iOS Feature: Enable log send functionality 

### ISSUE THREAD

**Issue by rinchen** [Free-Republic-of-Verdis/verdis-communications#5]
Feature:

As a user,
I want to be able send crash reports with logs to the developer,
so that bugs are fixed in new releases.

As a developer,
I want users to be able to send me crash reports,
so I can identify bugs in the application and release fixes.

**Comment by garv-shah** [comment]
I'm not too sure how possible this is inside the app, since the app doesn't get the crash report. I'm using TestFlight to be able to receive crash reports currently, so it may be beneficial if I give people like you the beta download link so I can get better reports and share them with you
besides that, I should probably implement [this](https://pub.dev/packages/firebase_crashlytics) so I can better monitor crashes in the release builds, which I plan to do in this bug update
I'll leave this open for now until I implement crashlytics, but yeah, I don't think it's possible in app since everything is platform specific when it comes to crashes

**Comment by rinchen** [comment]
I was thinking about crashlytics mostly so if that is easy for you to do, that would be enough for now I think.

**Comment by garv-shah** [comment]
cool, perfect, will add it in the next release!

**Comment by garv-shah** [comment]
added ! https://github.com/Free-Republic-of-Verdis/verdis-communications/commit/cad03dbf0601d0fb48c3f4fe6079b120ff29786d
